# === DEFAULT ===
[default.bot]
parse_mode = 'HTML'

[default.logs]
log_level = 'DEBUG'

[default.redis]
port = 6379

[default.postgres]
name = 'postgres_db'
port = 5432


# === PRODUCTION ===
[production.logs]
log_level = 'INFO'